version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./Docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8000:80"
    links:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: monolith_db
      DB_USERNAME: henry
      DB_PASSWORD: henry123
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: monolith_db
      POSTGRES_USER: henry
      POSTGRES_PASSWORD: henry123
    networks:
      - app-network
    volumes:
      - ./data/db:/var/lib/postgresql/data
networks:
  app-network:
    driver: bridge
